[package]
name = "jolt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
csv = "1.3.0"
prettytable-rs = "0.10.0"
sysinfo = "0.30.5"
